import fs from "fs";
import path from "path";
import type { AutoImportOptions } from "./type";
import type { Plugin, ResolvedConfig, ViteDevServer } from "vite";

/**
 * 将路径转换为 Unix 风格
 */
function slash(path: string): string {
	return path.replace(/\\/g, "/");
}

/**
 * Pascal Case 转换
 */
function pascalCase(str: string): string {
	return str.replace(/[-_](\w)/g, (_, c) => (c ? c.toUpperCase() : "")).replace(/^\w/, (c) => c.toUpperCase());
}

/**
 * 组件自动导入
 * @param options 选项
 */
function componentAutoImport(options: AutoImportOptions = {}): Plugin {
	const {
		dir = "src/components",
		exportPath = "src/components/index.ts",
		dts = true,
		dtsPath = "types/components.d.ts",
		deep = true,
		extensions = ["vue", "tsx", "jsx"],
		formatter,
	} = options;

	let config: ResolvedConfig;
	const componentMap = new Map<
		string,
		{
			/** 组件名称 (PascalCase) */
			name: string;
			/** 组件文件路径 (绝对路径) */
			from: string;
		}
	>();

	/** 从文件路径获取组件名 */
	const getNameFromPath = (filePath: string): string => {
		// 移除扩展名
		let name = filePath;
		for (const ext of extensions) {
			if (name.endsWith(`.${ext}`)) {
				name = name.slice(0, -ext.length - 1);
				break;
			}
		}

		// 如果是 index 文件，使用父目录名
		if (name.endsWith("/index") || name.endsWith("\\index")) {
			const parts = name.split(/[\\/]/);
			name = parts[parts.length - 2] || parts[parts.length - 1];
		} else {
			const parts = name.split(/[\\/]/);
			name = parts[parts.length - 1];
		}

		if (formatter) {
			return formatter(name);
		} else {
			return pascalCase(name);
		}
	};

	/** 递归扫描目录 */
	const scanDirectory = (dirPath: string, depth = 0): string[] => {
		const files: string[] = [];

		if (!fs.existsSync(dirPath)) {
			return files;
		}

		const entries = fs.readdirSync(dirPath, { withFileTypes: true });

		for (const entry of entries) {
			const fullPath = path.join(dirPath, entry.name);

			if (entry.isDirectory()) {
				// 跳过 node_modules 等
				if (entry.name === "node_modules" || entry.name.startsWith(". ")) {
					continue;
				}

				// 深度扫描
				if (deep || depth === 0) {
					files.push(...scanDirectory(fullPath, depth + 1));
				}
			} else if (entry.isFile()) {
				// 检查文件扩展名
				const ext = path.extname(entry.name).slice(1);
				if (extensions.includes(ext)) {
					files.push(fullPath);
				}
			}
		}

		return files;
	};

	/** 扫描组件文件 */
	const scanComponents = (): void => {
		componentMap.clear();

		const fullDir = path.resolve(config.root, dir);

		if (!fs.existsSync(fullDir)) {
			console.warn(`[component-auto-import] Directory not found: ${fullDir}`);
			return;
		}

		const files = scanDirectory(fullDir);

		files.forEach((absolutePath) => {
			const relativePath = path.relative(fullDir, absolutePath);
			const componentName = getNameFromPath(relativePath);

			componentMap.set(componentName, {
				name: componentName,
				from: absolutePath,
			});
		});
	};

	/** 生成自动注册文件 */
	const generateAutoRegister = (): void => {
		if (componentMap.size === 0) return;

		const components = Array.from(componentMap.values()).sort((a, b) => a.name.localeCompare(b.name));

		const registerFilePath = path.resolve(config.root, exportPath);
		const componentDir = path.dirname(registerFilePath);

		const lines: string[] = [];
		lines.push("/* eslint-disable */");
		lines.push("/* prettier-ignore */");
		lines.push("// @ts-nocheck");
		lines.push("// Auto-generated by fast component-auto-import");
		lines.push("// Generated by fast-vite-plugins");
		lines.push("// Do not edit this file manually");
		lines.push("");
		lines.push('import type { App } from "vue";');
		lines.push("");

		// 生成 import 语句
		components.forEach(({ name, from }) => {
			const relativePath = slash(path.relative(componentDir, from));
			const importPath = relativePath.startsWith(".") ? relativePath : `./${relativePath}`;
			lines.push(`import ${name} from "${importPath}";`);
			lines.push(`export { ${name} };`);
			lines.push(`export type ${name}Instance = InstanceType<typeof ${name}>;`);
		});

		lines.push("");
		lines.push("/** 自动注册所有组件 */");
		lines.push("export function registerComponents(app: App): void {");

		components.forEach(({ name }) => {
			lines.push(`	app.component(${name}.name, ${name});`);
		});

		lines.push("}");
		lines.push("");

		const code = `${lines.join("\n")}\n`;

		const existingCode = fs.existsSync(registerFilePath) ? fs.readFileSync(registerFilePath, "utf-8") : "";

		if (code !== existingCode) {
			fs.writeFileSync(registerFilePath, code, "utf-8");
		}
	};

	/** 生成类型声明文件 */
	const generateDts = (): void => {
		if (!dts || componentMap.size === 0) return;

		const components = Array.from(componentMap.values()).sort((a, b) => a.name.localeCompare(b.name));

		const dtsFullPath = path.resolve(config.root, dtsPath);
		const dtsDir = path.dirname(dtsFullPath);

		// 生成类型声明内容
		const lines: string[] = [];
		lines.push("// For this project development");
		lines.push("// Auto-generated by fast component-auto-import");
		lines.push("// Generated by fast-vite-plugins");
		lines.push("// Do not edit this file manually");
		lines.push("");
		lines.push('import "@vue/runtime-core";');
		lines.push("");
		lines.push("// GlobalComponents for Volar");
		lines.push('declare module "@vue/runtime-core" {');
		lines.push("	export interface GlobalComponents {");

		components.forEach(({ name, from }) => {
			// 计算相对路径
			let relativePath = slash(path.relative(dtsDir, from));

			// 移除文件扩展名
			relativePath = relativePath.replace(/\.(vue|tsx|jsx)$/, "");

			// 确保以 ./ 开头
			const importPath = relativePath.startsWith(".") ? relativePath : `./${relativePath}`;

			lines.push(`		${name}: (typeof import("${importPath}"))["default"];`);
		});

		lines.push("	}");
		lines.push("}");
		lines.push("");
		lines.push("export {};");

		const code = `${lines.join("\n")}\n`;

		// 确保目录存在
		if (!fs.existsSync(dtsDir)) {
			fs.mkdirSync(dtsDir, { recursive: true });
		}

		// 只有内容变化时才写入
		const existingCode = fs.existsSync(dtsFullPath) ? fs.readFileSync(dtsFullPath, "utf-8") : "";

		if (code !== existingCode) {
			fs.writeFileSync(dtsFullPath, code, "utf-8");
		}
	};

	return {
		name: "fast-vite-plugin-component-auto-import",
		enforce: "post",
		configResolved: (resolvedConfig: ResolvedConfig): void | Promise<void> => {
			// 存储最终解析的配置
			config = resolvedConfig;
		},
		buildStart(): void | Promise<void> {
			scanComponents();
			generateAutoRegister();
			generateDts();
		},
		// eslint-disable-next-line @typescript-eslint/explicit-function-return-type
		configureServer(server: ViteDevServer) {
			const fullDir = path.resolve(config.root, dir);

			// 监听文件变化
			if (fs.existsSync(fullDir)) {
				server.watcher.add(fullDir);

				const handle = (file: string): void => {
					if (!file) return;
					// 忽略 .d.ts 文件
					if (file.endsWith(".d.ts")) return;

					// 检查是否是组件文件
					const ext = path.extname(file).slice(1);
					if (!extensions.includes(ext)) return;

					scanComponents();
					generateAutoRegister();
					generateDts();
				};

				server.watcher.on("add", handle);
				server.watcher.on("change", handle);
				server.watcher.on("unlink", handle);
			}
		},
	};
}

export { componentAutoImport };
