export * from "./buildInfo";
export * from "./buildSvgIcon";
export * from "./bundleBudget";
export * from "./cdnImport";
export * from "./componentAutoImport";
export * from "./compression";
export * from "./devRestart";
export * from "./envGuard";
export * from "./htmlTemplate";
export * from "./routerPath";
export * from "./staticCopy";
export * from "./subresourceIntegrity";
export * from "./virtualModules";
export type { Awaitable, JsonPrimitive, JsonValue } from "./shared/plugin";
